baseURL: "https://example.com/"
languageCode: "en-us"
title: "My Storia Site"
theme: "storia"

params:
  description: "A beautiful Hugo theme for content creators"
  author: "Your Name"
  logo: "/images/logo.png"  # Place your logo in the static/images folder
  mainSections:
    - posts
    - articles
  
  # Theme customization
  colors:
    primary: "#3490dc"
    secondary: "#ffed4a"
    accent: "#8C2318"
    background: "#ffffff"
    text: "#2d3748"
    textLight: "#4a5568"
    navbarBg: "#2d3748"
    navbarText: "#ffffff"
  
  fonts:
    sans: "Open Sans"
    serif: "Merriweather"
  
  # Uncomment and modify this if you want to use custom fonts
  # customFonts:
  #   - "https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Lora:wght@400;700&display=swap"

  # Display options
  showPublishDate: true  # Set to false to hide publication dates

  # Social media links
  twitter: "https://twitter.com/yourusername"
  facebook: "https://facebook.com/yourusername"
  instagram: "https://instagram.com/yourusername"
  linkedin: "https://linkedin.com/in/yourusername"

  analytics:
    enabled: true
    provider: "umami"  # Can be "umami", "google", etc.
    umamiConfig:
      scriptUrl: "https://cloud.umami.is/script.js"
      websiteId: ""  # User will replace this with their ID
menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 2
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 3
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 4

# Hugo settings
disableKinds: ["RSS", "sitemap"]
pygmentsCodeFences: true
pygmentsUseClasses: true

# Pagination
paginate: 6
paginatePath: "page"

# Taxonomies
taxonomies:
  tag: "tags"
  category: "categories"